#!/usr/bin/env sh

# Add /home/kovaltct/texlive/2020/texmf-dist/doc/man to MANPATH.
# Add /home/kovaltct/texlive/2020/texmf-dist/doc/info to INFOPATH.
# Most importantly, add /home/kovaltct/texlive/2020/bin/x86_64-linux
# to your PATH for current and future sessions.

echo '' >> ~/.profile
echo '# >>> TeX Live >>>' >> ~/.profile 
echo 'export MANPATH=${MANPATH}:~/texlive/2020/texmf-dist/doc/man' >> ~/.profile
echo 'export INFOPATH=${INFOPATH}:~/texlive/2020/texmf-dist/doc/info' >> ~/.profile
echo 'export PATH=${PATH}:~/texlive/2020/bin/x86_64-linux' >> ~/.profile
echo '# <<< TeX Live <<<' >> ~/.profile
echo '# <<< installé grâce à T. Kovaltchouk <<<' >> ~/.profile
echo '' >> ~/.profile

